# Generated by Django 3.2.9 on 2021-11-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='middle_names',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
