# Generated by Django 3.2.9 on 2021-12-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_expertise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='expertise',
        ),
    ]
